### ISSUE TITLE
WvW Module

### ISSUE THREAD

**Issue by greaka** [blish-hud/Community-Module-Pack#86]
WvW camp flipping timers (with toggle option for herd icons)

**Comment by cubed-it** [comment]
I was just looking for this. It's a shame that it hasn't been around for so long.... That's somehow not a good outlook. 😢
I am absolutely for it, if someone has time and knowledge, please! 👌

**Comment by agaertner** [comment]
> I was just looking for this. It's a shame that it hasn't been around for so long.... That's somehow not a good outlook. 😢 I am absolutely for it, if someone has time and knowledge, please! 👌

It is just around the corner.  I just haven't released the module yet since the alliance betas breaks it and I wasn't sure if it will break with the release of EoD as well. Since then an ArenaNet employee has given us closure I will release the current version of the module in the next two days.

You can manually download a pre-release of said module called "Mistwar" here: https://github.com/agaertner/Blish-HUD-Modules-Releases/releases/tag/bh.blishhud%3E%3D0.11.1-ci.64
